### ISSUE TITLE
The Mix manifest does not exist

### ISSUE THREAD

**Issue by x3inspire** [SjorsO/subtitle-tools#30]
What should i do to fix this error?

`0 info it worked if it ends with ok 1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'run', 'development' ] 2 info using npm@6.10.0 3 info using node@v10.16.0 4 verbose run-script [ 'predevelopment', 'development', 'postdevelopment' ] 5 info lifecycle @~predevelopment: @ 6 info lifecycle @~development: @ 7 verbose lifecycle @~development: unsafe-perm in lifecycle true 8 verbose lifecycle @~development: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ubuntu/subtitle-tools/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home$ 9 verbose lifecycle @~development: CWD: /home/ubuntu/subtitle-tools 10 silly lifecycle @~development: Args: [ '-c', 10 silly lifecycle 'cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js' ] 11 silly lifecycle @~development: Returned: code: 1 signal: null 12 info lifecycle @~development: Failed to exec development script 13 verbose stack Error: @ development: cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js13 verbose stack Exit status 1 13 verbose stack at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16) 13 verbose stack at EventEmitter.emit (events.js:198:13) 13 verbose stack at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14) 13 verbose stack at ChildProcess.emit (events.js:198:13) 13 verbose stack at maybeClose (internal/child_process.js:982:16) 13 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5) 14 verbose pkgid @ 15 verbose cwd /home/ubuntu/subtitle-tools 16 verbose Linux 4.15.0-1043-aws 17 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "run" "development" 18 verbose node v10.16.0 19 verbose npm v6.10.0 20 error code ELIFECYCLE 21 error errno 1 22 error @ development:cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js 22 error Exit status 1 23 error Failed at the @ development script. 23 error This is probably not a problem with npm. There is likely additional logging output above. 24 verbose exit [ 1, true ]`

> /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Foundation/Mix.php

`                return new HtmlString(Str::after($url, ':').$path);
            }
 
            return new HtmlString("//localhost:8080{$path}");
        }
 
        $manifestPath = public_path($manifestDirectory.'/mix-manifest.json');
 
        if (! isset($manifests[$manifestPath])) {
            if (! file_exists($manifestPath)) {
                throw new Exception('The Mix manifest does not exist.');
            }
 
            $manifests[$manifestPath] = json_decode(file_get_contents($manifestPath), true);
        }
 
        $manifest = $manifests[$manifestPath];
 
        if (! isset($manifest[$path])) {
            $exception = new Exception("Unable to locate Mix file: {$path}.");
 
            if (! app('config')->get('app.debug')) {
                report($exception);
 
                return $path;
            } else {`

> "The Mix manifest does not exist. (View: /home/ubuntu/subtitle-tools/resources/views/layout/base-template.blade.php) (View: /home/ubuntu/subtitle-tools/resources/views/layout/base-template.blade.php) (View: /home/ubuntu/subtitle-tools/resources/views/layout/base-template.blade.php)

**Comment by SjorsO** [comment]
I can't help you with these kinds of technical problems. Please use google instead.

**Comment by x3inspire** [comment]
Why you keep closed the thread? At least ask me more information please?  You keep asked me for google.

`ErrorException thrown with message "The Mix manifest does not exist. (View: /home/ubuntu/subtitle-tools/resources/views/layout/base-template.blade.php) (View: /home/ubuntu/subtitle-tools/resources/views/layout/base-template.blade.php) (View: /home/ubuntu/subtitle-tools/resources/views/layout/base-template.blade.php)"

Stacktrace:
#84 ErrorException in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Foundation/Mix.php:46
#83 Illuminate\View\Engines\CompilerEngine:handleViewException in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:45
#82 ErrorException in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Foundation/Mix.php:46
#81 Illuminate\View\Engines\CompilerEngine:handleViewException in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:45
#80 ErrorException in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Foundation/Mix.php:46
#79 Illuminate\View\Engines\CompilerEngine:handleViewException in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:45
#78 Exception in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Foundation/Mix.php:46
#77 Illuminate\Foundation\Mix:__invoke in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:579
#76 mix in /home/ubuntu/subtitle-tools/storage/framework/views/e4496f18231c3fe13a80ebceb1368a038d8bd1d7.php:26
#75 include in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:43
#74 Illuminate\View\Engines\PhpEngine:evaluatePath in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php:59
#73 Illuminate\View\Engines\CompilerEngine:get in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/View/View.php:142
#72 Illuminate\View\View:getContents in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/View/View.php:125
#71 Illuminate\View\View:renderContents in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/View/View.php:90
#70 Illuminate\View\View:render in /home/ubuntu/subtitle-tools/storage/framework/views/acf2b520cf5a1b07b843f8d17ad2ee26de9bb3c8.php:20
#69 include in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:43
#68 Illuminate\View\Engines\PhpEngine:evaluatePath in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php:59
#67 Illuminate\View\Engines\CompilerEngine:get in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/View/View.php:142
#66 Illuminate\View\View:getContents in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/View/View.php:125
#65 Illuminate\View\View:renderContents in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/View/View.php:90
#64 Illuminate\View\View:render in /home/ubuntu/subtitle-tools/storage/framework/views/b44d9321aebbeb8a19a3d8c12faa0dda699be414.php:126
#63 include in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:43
#62 Illuminate\View\Engines\PhpEngine:evaluatePath in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php:59
#61 Illuminate\View\Engines\CompilerEngine:get in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/View/View.php:142
#60 Illuminate\View\View:getContents in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/View/View.php:125
#59 Illuminate\View\View:renderContents in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/View/View.php:90
#58 Illuminate\View\View:render in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Http/Response.php:42
#57 Illuminate\Http\Response:setContent in /home/ubuntu/subtitle-tools/vendor/symfony/http-foundation/Response.php:202
#56 Symfony\Component\HttpFoundation\Response:__construct in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php:748
#55 Illuminate\Routing\Router:toResponse in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php:720
#54 Illuminate\Routing\Router:prepareResponse in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php:680
#53 Illuminate\Routing\Router:Illuminate\Routing\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#52 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php:50
#51 Laravel\Passport\Http\Middleware\CreateFreshApiToken:handle in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#50 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#49 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/ubuntu/subtitle-tools/app/Http/Middleware/TransformsRequestFiles.php:15
#48 App\Http\Middleware\TransformsRequestFiles:handle in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#47 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#46 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/ubuntu/subtitle-tools/app/Http/Middleware/CountUploadedFiles.php:32
#45 App\Http\Middleware\CountUploadedFiles:handle in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#44 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#43 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/ubuntu/subtitle-tools/app/Http/Middleware/RecordUploadedFileMimes.php:18
#42 App\Http\Middleware\RecordUploadedFileMimes:handle in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#41 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#40 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
#39 Illuminate\Routing\Middleware\SubstituteBindings:handle in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#38 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#37 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:75
#36 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#35 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#34 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
#33 Illuminate\View\Middleware\ShareErrorsFromSession:handle in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#32 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#31 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:56
#30 Illuminate\Session\Middleware\StartSession:handle in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#29 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#28 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
#27 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#26 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#25 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:66
#24 Illuminate\Cookie\Middleware\EncryptCookies:handle in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#23 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#22 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
#21 Illuminate\Pipeline\Pipeline:then in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php:682
#20 Illuminate\Routing\Router:runRouteWithinStack in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php:657
#19 Illuminate\Routing\Router:runRoute in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php:623
#18 Illuminate\Routing\Router:dispatchToRoute in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Routing/Router.php:612
#17 Illuminate\Routing\Router:dispatch in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
#16 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#15 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
#14 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#12 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21
#11 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
#8 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#6 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:62
#5 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:163
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#3 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
#2 Illuminate\Pipeline\Pipeline:then in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /home/ubuntu/subtitle-tools/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in /home/ubuntu/subtitle-tools/public/index.php:55
`
And this thing not related with the script error?
