### ISSUE TITLE
The sub/idx file can not be read

### ISSUE THREAD

**Issue by x3inspire** [SjorsO/subtitle-tools#31]
Hi, i hope this one you really can help me :)

I uploaded .sub and .idx and got this error:

> The sub/idx file can not be read

`[2019-07-11 13:07:59] production.ERROR: Missing required parameters for [Route: subIdx.show] [URI: convert-sub-idx-to-srt-online/{urlKey}]. (View: /resources/views/admin/sub-idx.blade.php) {"userId":"abcce46c-f0ad-3959-a411-166adc4e686c","exception":"[object] (ErrorException(code: 0): Missing required parameters for [Route: subIdx.show] [URI: convert-sub-idx-to-srt-online/{urlKey}]. (View: /resources/views/admin/sub-idx.blade.php) at /vendor/laravel/framework/src/Illuminate/Routing/Exceptions/UrlGenerationException.php:17, Illuminate\\Routing\\Exceptions\\UrlGenerationException(code: 0): Missing required parameters for [Route: subIdx.show] [URI: convert-sub-idx-to-srt-online/{urlKey}]. at /vendor/laravel/framework/src/Illuminate/Routing/Exceptions/UrlGenerationException.php:17)`

What should i do?

**Comment by SjorsO** [comment]
The questions you are asking are about normal Laravel things. You can find the answers you need on Google. You can also learn about Laravel at https://laracasts.com/
